services:
  # Main Application - Running on Port 8002 (Proxied by Host)
  web:
    build: .
    container_name: tib_cigar_app
    restart: always
    ports:
      - "8002:8000"
    volumes:
      - ./data:/app/data # Persist Database
      - ./static/uploads:/app/static/uploads # Persist User Uploads
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///data/tib_saas.db
    networks:
      - web_network

networks:
  web_network:


volumes:
  data:
